### ISSUE TITLE
[개선][kuke-board] Hibernate 쿼리 파라미터 출력 설정

### ISSUE THREAD

**Issue by pej4303** [pej4303/inflearn-pjt#4]
**📌 프로젝트명** : kuke-board
---

> 버전 정보
>  + Spring Boot 3.4.5
>  + Hibernate 6.6.13

## 1. 📖 도입 배경
+   테스트 시 실행되는 SQL 쿼리의 파라미터 값이 로그에 명확히 드러나지 않아 디버깅이 불편했다.
+   쿼리 로그를 보다 직관적으로 확인할 수 있도록 설정이 필요했다.
---

##  2. 🔍 적용 방법
1. application.yml에 적용
```yaml
spring:    
  jpa:  
    properties:  
      hibernate:  
        format_sql: true        # SQL 쿼리를 포맷팅해서 보기 좋게 출력
        use_sql_comments: true  # SQL에 주석 추가
logging:  
  level:  
    org.hibernate.orm.jdbc.bind: trace  # 바인딩된 쿼리 파라미터 출력

```

![Image](https://github.com/user-attachments/assets/63d23f11-9c96-432a-82a1-a7f64be2663c)

## 3. 📚 참조 자료 
+ https://byunsw4.tistory.com/25
